"""add canvas version_counter and operations log

Revision ID: 4aee2419fac1
Revises: 61880c3e0446
Create Date: 2026-06-17 21:52:13.028868

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aee2419fac1'
down_revision: str | None = '61880c3e0446'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('canvas_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('op_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('client_op_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_id', 'client_op_id', name='uq_operation_canvas_client_op'),
    sa.UniqueConstraint('canvas_id', 'version', name='uq_operation_canvas_version')
    )
    op.create_index(op.f('ix_operations_canvas_id'), 'operations', ['canvas_id'], unique=False)
    op.add_column('canvases', sa.Column('version_counter', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canvases', 'version_counter')
    op.drop_index(op.f('ix_operations_canvas_id'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
